/*
 * vllm.cpp VENDORED Triton AOT artifact — GENERATED CODE. DO NOT EDIT.
 *
 * Generated by `scripts/triton-aot-compile.py` / `triton.tools.link` from
 * triton_kernels/solve_tril.py (kernel merge_16x16_to_64x64_inverse_kernel); the embedded byte
 * array (if any) is the compiled cubin for the arch named by this
 * directory. Generator versions, kernel-source hashes and the exact
 * generation parameters are recorded in the MANIFEST next to this file.
 *
 * Regenerate (MAINTAINER task; needs Python + Triton + ptxas):
 *   scripts/regen-triton-aot.sh
 *
 * The generating kernel source (triton_kernels/solve_tril.py) is ported
 * verbatim from flash-linear-attention via vLLM (MIT; see its header);
 * this generated artifact is distributed under the repository's
 * Apache-2.0 license (see LICENSE and NOTICE).
 */
#ifndef TT_LINK_INCLUDES
#define TT_LINK_INCLUDES

#include <stdint.h>

#include <cuda.h>

typedef CUstream TT_StreamTy;
typedef CUresult TT_ResultTy;

#define TT_ERROR_INVALID_VALUE CUDA_ERROR_INVALID_VALUE

#endif
#include <stdint.h>
#include <assert.h>

// launcher for: gdn_tril_h32_32x64x1_warps4xstages3
CUresult gdn_tril_h32_31103791_0d1d2d3d(CUstream stream, CUdeviceptr A, CUdeviceptr Ai, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT);

CUresult gdn_tril_h32_32x64x1_warps4xstages3(CUstream stream, CUdeviceptr A, CUdeviceptr Ai, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT){
  if (((uintptr_t)A % 16 == 0) && ((uintptr_t)Ai % 16 == 0) && ((uintptr_t)cu_seqlens % 16 == 0) && ((uintptr_t)chunk_indices % 16 == 0))
    return gdn_tril_h32_31103791_0d1d2d3d(stream, A, Ai, cu_seqlens, chunk_indices, T, NT);

  return TT_ERROR_INVALID_VALUE;
}

// load for: gdn_tril_h32_32x64x1_warps4xstages3
void load_gdn_tril_h32_31103791_0d1d2d3d();
void load_gdn_tril_h32_32x64x1_warps4xstages3() {
  load_gdn_tril_h32_31103791_0d1d2d3d();
}

// unload for: gdn_tril_h32_32x64x1_warps4xstages3
void unload_gdn_tril_h32_31103791_0d1d2d3d();
void unload_gdn_tril_h32_32x64x1_warps4xstages3() {
  unload_gdn_tril_h32_31103791_0d1d2d3d();
}

typedef CUresult (*kernel_func_t)(CUstream stream, CUdeviceptr A, CUdeviceptr Ai, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT);
kernel_func_t gdn_tril_h32_kernels[] = {
  gdn_tril_h32_32x64x1_warps4xstages3,
};

int gdn_tril_h32_get_num_algos(void){
  return (int)(sizeof(gdn_tril_h32_kernels) / sizeof(gdn_tril_h32_kernels[0]));
}

CUresult gdn_tril_h32(CUstream stream, CUdeviceptr A, CUdeviceptr Ai, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT, int algo_id){
  assert (algo_id < (int)sizeof(gdn_tril_h32_kernels));
  return gdn_tril_h32_kernels[algo_id](stream, A, Ai, cu_seqlens, chunk_indices, T, NT);
}

void load_gdn_tril_h32(void){
  load_gdn_tril_h32_32x64x1_warps4xstages3();
}

void unload_gdn_tril_h32(void){
  unload_gdn_tril_h32_32x64x1_warps4xstages3();
}


CUresult gdn_tril_h32_default(CUstream stream, CUdeviceptr A, CUdeviceptr Ai, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT){
  return gdn_tril_h32(stream, A, Ai, cu_seqlens, chunk_indices, T, NT, 0);
}
