/*
 * vllm.cpp VENDORED Triton AOT artifact — GENERATED CODE. DO NOT EDIT.
 *
 * Generated by `scripts/triton-aot-compile.py` / `triton.tools.link` from
 * triton_kernels/fused_recurrent_packed_decode.py (kernel fused_recurrent_gated_delta_rule_packed_decode_kernel); the embedded byte
 * array (if any) is the compiled cubin for the arch named by this
 * directory. Generator versions, kernel-source hashes and the exact
 * generation parameters are recorded in the MANIFEST next to this file.
 *
 * Regenerate (MAINTAINER task; needs Python + Triton + ptxas):
 *   scripts/regen-triton-aot.sh
 *
 * The generating kernel source (triton_kernels/fused_recurrent_packed_decode.py) is ported
 * verbatim from flash-linear-attention via vLLM (MIT; see its header);
 * this generated artifact is distributed under the repository's
 * Apache-2.0 license (see LICENSE and NOTICE).
 */
#ifndef TT_LINK_INCLUDES
#define TT_LINK_INCLUDES

#include <stdint.h>

#include <cuda.h>

typedef CUstream TT_StreamTy;
typedef CUresult TT_ResultTy;

#define TT_ERROR_INVALID_VALUE CUDA_ERROR_INVALID_VALUE

#endif
#include <stdint.h>
#include <assert.h>

// launcher for: gdn_decode_h48_10240x96x96x786432x786432x1x16x48x128x128x128x32x20x1_warps1xstages3
CUresult gdn_decode_h48_81e5f031_0d1d2d3d4d5d6d7d8d(CUstream stream, CUdeviceptr mixed_qkv, CUdeviceptr a, CUdeviceptr b, CUdeviceptr A_log, CUdeviceptr dt_bias, CUdeviceptr o, CUdeviceptr h0, CUdeviceptr ht, CUdeviceptr ssm_state_indices, int32_t NBH);

CUresult gdn_decode_h48_10240x96x96x786432x786432x1x16x48x128x128x128x32x20x1_warps1xstages3(CUstream stream, CUdeviceptr mixed_qkv, CUdeviceptr a, CUdeviceptr b, CUdeviceptr A_log, CUdeviceptr dt_bias, CUdeviceptr o, CUdeviceptr h0, CUdeviceptr ht, CUdeviceptr ssm_state_indices, int32_t NBH){
  if (((uintptr_t)mixed_qkv % 16 == 0) && ((uintptr_t)a % 16 == 0) && ((uintptr_t)b % 16 == 0) && ((uintptr_t)A_log % 16 == 0) && ((uintptr_t)dt_bias % 16 == 0) && ((uintptr_t)o % 16 == 0) && ((uintptr_t)h0 % 16 == 0) && ((uintptr_t)ht % 16 == 0) && ((uintptr_t)ssm_state_indices % 16 == 0))
    return gdn_decode_h48_81e5f031_0d1d2d3d4d5d6d7d8d(stream, mixed_qkv, a, b, A_log, dt_bias, o, h0, ht, ssm_state_indices, NBH);

  return TT_ERROR_INVALID_VALUE;
}

// load for: gdn_decode_h48_10240x96x96x786432x786432x1x16x48x128x128x128x32x20x1_warps1xstages3
void load_gdn_decode_h48_81e5f031_0d1d2d3d4d5d6d7d8d();
void load_gdn_decode_h48_10240x96x96x786432x786432x1x16x48x128x128x128x32x20x1_warps1xstages3() {
  load_gdn_decode_h48_81e5f031_0d1d2d3d4d5d6d7d8d();
}

// unload for: gdn_decode_h48_10240x96x96x786432x786432x1x16x48x128x128x128x32x20x1_warps1xstages3
void unload_gdn_decode_h48_81e5f031_0d1d2d3d4d5d6d7d8d();
void unload_gdn_decode_h48_10240x96x96x786432x786432x1x16x48x128x128x128x32x20x1_warps1xstages3() {
  unload_gdn_decode_h48_81e5f031_0d1d2d3d4d5d6d7d8d();
}

typedef CUresult (*kernel_func_t)(CUstream stream, CUdeviceptr mixed_qkv, CUdeviceptr a, CUdeviceptr b, CUdeviceptr A_log, CUdeviceptr dt_bias, CUdeviceptr o, CUdeviceptr h0, CUdeviceptr ht, CUdeviceptr ssm_state_indices, int32_t NBH);
kernel_func_t gdn_decode_h48_kernels[] = {
  gdn_decode_h48_10240x96x96x786432x786432x1x16x48x128x128x128x32x20x1_warps1xstages3,
};

int gdn_decode_h48_get_num_algos(void){
  return (int)(sizeof(gdn_decode_h48_kernels) / sizeof(gdn_decode_h48_kernels[0]));
}

CUresult gdn_decode_h48(CUstream stream, CUdeviceptr mixed_qkv, CUdeviceptr a, CUdeviceptr b, CUdeviceptr A_log, CUdeviceptr dt_bias, CUdeviceptr o, CUdeviceptr h0, CUdeviceptr ht, CUdeviceptr ssm_state_indices, int32_t NBH, int algo_id){
  assert (algo_id < (int)sizeof(gdn_decode_h48_kernels));
  return gdn_decode_h48_kernels[algo_id](stream, mixed_qkv, a, b, A_log, dt_bias, o, h0, ht, ssm_state_indices, NBH);
}

void load_gdn_decode_h48(void){
  load_gdn_decode_h48_10240x96x96x786432x786432x1x16x48x128x128x128x32x20x1_warps1xstages3();
}

void unload_gdn_decode_h48(void){
  unload_gdn_decode_h48_10240x96x96x786432x786432x1x16x48x128x128x128x32x20x1_warps1xstages3();
}


CUresult gdn_decode_h48_default(CUstream stream, CUdeviceptr mixed_qkv, CUdeviceptr a, CUdeviceptr b, CUdeviceptr A_log, CUdeviceptr dt_bias, CUdeviceptr o, CUdeviceptr h0, CUdeviceptr ht, CUdeviceptr ssm_state_indices, int32_t NBH){
  return gdn_decode_h48(stream, mixed_qkv, a, b, A_log, dt_bias, o, h0, ht, ssm_state_indices, NBH, 0);
}
