/*
 * vllm.cpp VENDORED Triton AOT artifact — GENERATED CODE. DO NOT EDIT.
 *
 * Generated by `scripts/triton-aot-compile.py` / `triton.tools.link` from
 * triton_kernels/chunk_o.py (kernel chunk_fwd_kernel_o); the embedded byte
 * array (if any) is the compiled cubin for the arch named by this
 * directory. Generator versions, kernel-source hashes and the exact
 * generation parameters are recorded in the MANIFEST next to this file.
 *
 * Regenerate (MAINTAINER task; needs Python + Triton + ptxas):
 *   scripts/regen-triton-aot.sh
 *
 * The generating kernel source (triton_kernels/chunk_o.py) is ported
 * verbatim from flash-linear-attention via vLLM (MIT; see its header);
 * this generated artifact is distributed under the repository's
 * Apache-2.0 license (see LICENSE and NOTICE).
 */
#ifndef TT_LINK_INCLUDES
#define TT_LINK_INCLUDES

#include <stdint.h>

#include <cuda.h>

typedef CUstream TT_StreamTy;
typedef CUresult TT_ResultTy;

#define TT_ERROR_INVALID_VALUE CUDA_ERROR_INVALID_VALUE

#endif
#include <stdint.h>
#include <assert.h>

// launcher for: gdn_chunko_h48_48x16x128x128x64x64x64x1x1_warps4xstages3
CUresult gdn_chunko_h48_6ce8cd41_0d1d2d3d4d5d6d7d(CUstream stream, CUdeviceptr q, CUdeviceptr k, CUdeviceptr v, CUdeviceptr h, CUdeviceptr g, CUdeviceptr o, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT);

CUresult gdn_chunko_h48_48x16x128x128x64x64x64x1x1_warps4xstages3(CUstream stream, CUdeviceptr q, CUdeviceptr k, CUdeviceptr v, CUdeviceptr h, CUdeviceptr g, CUdeviceptr o, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT){
  if (((uintptr_t)q % 16 == 0) && ((uintptr_t)k % 16 == 0) && ((uintptr_t)v % 16 == 0) && ((uintptr_t)h % 16 == 0) && ((uintptr_t)g % 16 == 0) && ((uintptr_t)o % 16 == 0) && ((uintptr_t)cu_seqlens % 16 == 0) && ((uintptr_t)chunk_indices % 16 == 0))
    return gdn_chunko_h48_6ce8cd41_0d1d2d3d4d5d6d7d(stream, q, k, v, h, g, o, cu_seqlens, chunk_indices, T, NT);

  return TT_ERROR_INVALID_VALUE;
}

// load for: gdn_chunko_h48_48x16x128x128x64x64x64x1x1_warps4xstages3
void load_gdn_chunko_h48_6ce8cd41_0d1d2d3d4d5d6d7d();
void load_gdn_chunko_h48_48x16x128x128x64x64x64x1x1_warps4xstages3() {
  load_gdn_chunko_h48_6ce8cd41_0d1d2d3d4d5d6d7d();
}

// unload for: gdn_chunko_h48_48x16x128x128x64x64x64x1x1_warps4xstages3
void unload_gdn_chunko_h48_6ce8cd41_0d1d2d3d4d5d6d7d();
void unload_gdn_chunko_h48_48x16x128x128x64x64x64x1x1_warps4xstages3() {
  unload_gdn_chunko_h48_6ce8cd41_0d1d2d3d4d5d6d7d();
}

typedef CUresult (*kernel_func_t)(CUstream stream, CUdeviceptr q, CUdeviceptr k, CUdeviceptr v, CUdeviceptr h, CUdeviceptr g, CUdeviceptr o, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT);
kernel_func_t gdn_chunko_h48_kernels[] = {
  gdn_chunko_h48_48x16x128x128x64x64x64x1x1_warps4xstages3,
};

int gdn_chunko_h48_get_num_algos(void){
  return (int)(sizeof(gdn_chunko_h48_kernels) / sizeof(gdn_chunko_h48_kernels[0]));
}

CUresult gdn_chunko_h48(CUstream stream, CUdeviceptr q, CUdeviceptr k, CUdeviceptr v, CUdeviceptr h, CUdeviceptr g, CUdeviceptr o, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT, int algo_id){
  assert (algo_id < (int)sizeof(gdn_chunko_h48_kernels));
  return gdn_chunko_h48_kernels[algo_id](stream, q, k, v, h, g, o, cu_seqlens, chunk_indices, T, NT);
}

void load_gdn_chunko_h48(void){
  load_gdn_chunko_h48_48x16x128x128x64x64x64x1x1_warps4xstages3();
}

void unload_gdn_chunko_h48(void){
  unload_gdn_chunko_h48_48x16x128x128x64x64x64x1x1_warps4xstages3();
}


CUresult gdn_chunko_h48_default(CUstream stream, CUdeviceptr q, CUdeviceptr k, CUdeviceptr v, CUdeviceptr h, CUdeviceptr g, CUdeviceptr o, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT){
  return gdn_chunko_h48(stream, q, k, v, h, g, o, cu_seqlens, chunk_indices, T, NT, 0);
}
