/*
 * vllm.cpp VENDORED Triton AOT artifact — GENERATED CODE. DO NOT EDIT.
 *
 * Generated by `scripts/triton-aot-compile.py` / `triton.tools.link` from
 * triton_kernels/chunk_kda_kkt.py (kernel chunk_kda_scaled_dot_kkt_fwd_kernel_intra_sub_inter); the embedded byte
 * array (if any) is the compiled cubin for the arch named by this
 * directory. Generator versions, kernel-source hashes and the exact
 * generation parameters are recorded in the MANIFEST next to this file.
 *
 * Regenerate (MAINTAINER task; needs Python + Triton + ptxas):
 *   scripts/regen-triton-aot.sh
 *
 * The generating kernel source (triton_kernels/chunk_kda_kkt.py) is ported
 * verbatim from flash-linear-attention via vLLM (MIT; see its header);
 * this generated artifact is distributed under the repository's
 * Apache-2.0 license (see LICENSE and NOTICE).
 */
#ifndef TT_LINK_INCLUDES
#define TT_LINK_INCLUDES

#include <stdint.h>

#include <cuda.h>

typedef CUstream TT_StreamTy;
typedef CUresult TT_ResultTy;

#define TT_ERROR_INVALID_VALUE CUDA_ERROR_INVALID_VALUE

#endif
#include <stdint.h>
#include <assert.h>

// launcher for: kda_kkt_inter_32x128x64x16x64x4x1_warps4xstages3
CUresult kda_kkt_inter_8cabd344_0d1d2d3d4d5d6d7d(CUstream stream, CUdeviceptr q, CUdeviceptr k, CUdeviceptr g, CUdeviceptr beta, CUdeviceptr A, CUdeviceptr Aqk, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT);

CUresult kda_kkt_inter_32x128x64x16x64x4x1_warps4xstages3(CUstream stream, CUdeviceptr q, CUdeviceptr k, CUdeviceptr g, CUdeviceptr beta, CUdeviceptr A, CUdeviceptr Aqk, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT){
  if (((uintptr_t)q % 16 == 0) && ((uintptr_t)k % 16 == 0) && ((uintptr_t)g % 16 == 0) && ((uintptr_t)beta % 16 == 0) && ((uintptr_t)A % 16 == 0) && ((uintptr_t)Aqk % 16 == 0) && ((uintptr_t)cu_seqlens % 16 == 0) && ((uintptr_t)chunk_indices % 16 == 0))
    return kda_kkt_inter_8cabd344_0d1d2d3d4d5d6d7d(stream, q, k, g, beta, A, Aqk, cu_seqlens, chunk_indices, T, NT);

  return TT_ERROR_INVALID_VALUE;
}

// load for: kda_kkt_inter_32x128x64x16x64x4x1_warps4xstages3
void load_kda_kkt_inter_8cabd344_0d1d2d3d4d5d6d7d();
void load_kda_kkt_inter_32x128x64x16x64x4x1_warps4xstages3() {
  load_kda_kkt_inter_8cabd344_0d1d2d3d4d5d6d7d();
}

// unload for: kda_kkt_inter_32x128x64x16x64x4x1_warps4xstages3
void unload_kda_kkt_inter_8cabd344_0d1d2d3d4d5d6d7d();
void unload_kda_kkt_inter_32x128x64x16x64x4x1_warps4xstages3() {
  unload_kda_kkt_inter_8cabd344_0d1d2d3d4d5d6d7d();
}

typedef CUresult (*kernel_func_t)(CUstream stream, CUdeviceptr q, CUdeviceptr k, CUdeviceptr g, CUdeviceptr beta, CUdeviceptr A, CUdeviceptr Aqk, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT);
kernel_func_t kda_kkt_inter_kernels[] = {
  kda_kkt_inter_32x128x64x16x64x4x1_warps4xstages3,
};

int kda_kkt_inter_get_num_algos(void){
  return (int)(sizeof(kda_kkt_inter_kernels) / sizeof(kda_kkt_inter_kernels[0]));
}

CUresult kda_kkt_inter(CUstream stream, CUdeviceptr q, CUdeviceptr k, CUdeviceptr g, CUdeviceptr beta, CUdeviceptr A, CUdeviceptr Aqk, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT, int algo_id){
  assert (algo_id < (int)sizeof(kda_kkt_inter_kernels));
  return kda_kkt_inter_kernels[algo_id](stream, q, k, g, beta, A, Aqk, cu_seqlens, chunk_indices, T, NT);
}

void load_kda_kkt_inter(void){
  load_kda_kkt_inter_32x128x64x16x64x4x1_warps4xstages3();
}

void unload_kda_kkt_inter(void){
  unload_kda_kkt_inter_32x128x64x16x64x4x1_warps4xstages3();
}


CUresult kda_kkt_inter_default(CUstream stream, CUdeviceptr q, CUdeviceptr k, CUdeviceptr g, CUdeviceptr beta, CUdeviceptr A, CUdeviceptr Aqk, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT){
  return kda_kkt_inter(stream, q, k, g, beta, A, Aqk, cu_seqlens, chunk_indices, T, NT, 0);
}
