/*
 * vllm.cpp VENDORED Triton AOT artifact — GENERATED CODE. DO NOT EDIT.
 *
 * Generated by `scripts/triton-aot-compile.py` / `triton.tools.link` from
 * triton_kernels/chunk_delta_h.py (kernel chunk_gated_delta_rule_fwd_kernel_h_blockdim64); the embedded byte
 * array (if any) is the compiled cubin for the arch named by this
 * directory. Generator versions, kernel-source hashes and the exact
 * generation parameters are recorded in the MANIFEST next to this file.
 *
 * Regenerate (MAINTAINER task; needs Python + Triton + ptxas):
 *   scripts/regen-triton-aot.sh
 *
 * The generating kernel source (triton_kernels/chunk_delta_h.py) is ported
 * verbatim from flash-linear-attention via vLLM (MIT; see its header);
 * this generated artifact is distributed under the repository's
 * Apache-2.0 license (see LICENSE and NOTICE).
 */
#ifndef TT_LINK_INCLUDES
#define TT_LINK_INCLUDES

#include <stdint.h>

#include <cuda.h>

typedef CUstream TT_StreamTy;
typedef CUresult TT_ResultTy;

#define TT_ERROR_INVALID_VALUE CUDA_ERROR_INVALID_VALUE

#endif
#include <stdint.h>
#include <assert.h>

// launcher for: kda_deltah_h32_32x32x128x128x64x64x0x1x1x1x1x1x1_warps4xstages3
CUresult kda_deltah_h32_87804e73_0d1d2d3d5d6d7d8d9d10d(CUstream stream, CUdeviceptr k, CUdeviceptr v, CUdeviceptr w, CUdeviceptr v_new, CUdeviceptr g, CUdeviceptr gk, CUdeviceptr h, CUdeviceptr h0, CUdeviceptr ht, CUdeviceptr cu_seqlens, CUdeviceptr chunk_offsets, int32_t T, int32_t NH);

CUresult kda_deltah_h32_32x32x128x128x64x64x0x1x1x1x1x1x1_warps4xstages3(CUstream stream, CUdeviceptr k, CUdeviceptr v, CUdeviceptr w, CUdeviceptr v_new, CUdeviceptr g, CUdeviceptr gk, CUdeviceptr h, CUdeviceptr h0, CUdeviceptr ht, CUdeviceptr cu_seqlens, CUdeviceptr chunk_offsets, int32_t T, int32_t NH){
  if (((uintptr_t)k % 16 == 0) && ((uintptr_t)v % 16 == 0) && ((uintptr_t)w % 16 == 0) && ((uintptr_t)v_new % 16 == 0) && ((uintptr_t)gk % 16 == 0) && ((uintptr_t)h % 16 == 0) && ((uintptr_t)h0 % 16 == 0) && ((uintptr_t)ht % 16 == 0) && ((uintptr_t)cu_seqlens % 16 == 0) && ((uintptr_t)chunk_offsets % 16 == 0))
    return kda_deltah_h32_87804e73_0d1d2d3d5d6d7d8d9d10d(stream, k, v, w, v_new, g, gk, h, h0, ht, cu_seqlens, chunk_offsets, T, NH);

  return TT_ERROR_INVALID_VALUE;
}

// load for: kda_deltah_h32_32x32x128x128x64x64x0x1x1x1x1x1x1_warps4xstages3
void load_kda_deltah_h32_87804e73_0d1d2d3d5d6d7d8d9d10d();
void load_kda_deltah_h32_32x32x128x128x64x64x0x1x1x1x1x1x1_warps4xstages3() {
  load_kda_deltah_h32_87804e73_0d1d2d3d5d6d7d8d9d10d();
}

// unload for: kda_deltah_h32_32x32x128x128x64x64x0x1x1x1x1x1x1_warps4xstages3
void unload_kda_deltah_h32_87804e73_0d1d2d3d5d6d7d8d9d10d();
void unload_kda_deltah_h32_32x32x128x128x64x64x0x1x1x1x1x1x1_warps4xstages3() {
  unload_kda_deltah_h32_87804e73_0d1d2d3d5d6d7d8d9d10d();
}

typedef CUresult (*kernel_func_t)(CUstream stream, CUdeviceptr k, CUdeviceptr v, CUdeviceptr w, CUdeviceptr v_new, CUdeviceptr g, CUdeviceptr gk, CUdeviceptr h, CUdeviceptr h0, CUdeviceptr ht, CUdeviceptr cu_seqlens, CUdeviceptr chunk_offsets, int32_t T, int32_t NH);
kernel_func_t kda_deltah_h32_kernels[] = {
  kda_deltah_h32_32x32x128x128x64x64x0x1x1x1x1x1x1_warps4xstages3,
};

int kda_deltah_h32_get_num_algos(void){
  return (int)(sizeof(kda_deltah_h32_kernels) / sizeof(kda_deltah_h32_kernels[0]));
}

CUresult kda_deltah_h32(CUstream stream, CUdeviceptr k, CUdeviceptr v, CUdeviceptr w, CUdeviceptr v_new, CUdeviceptr g, CUdeviceptr gk, CUdeviceptr h, CUdeviceptr h0, CUdeviceptr ht, CUdeviceptr cu_seqlens, CUdeviceptr chunk_offsets, int32_t T, int32_t NH, int algo_id){
  assert (algo_id < (int)sizeof(kda_deltah_h32_kernels));
  return kda_deltah_h32_kernels[algo_id](stream, k, v, w, v_new, g, gk, h, h0, ht, cu_seqlens, chunk_offsets, T, NH);
}

void load_kda_deltah_h32(void){
  load_kda_deltah_h32_32x32x128x128x64x64x0x1x1x1x1x1x1_warps4xstages3();
}

void unload_kda_deltah_h32(void){
  unload_kda_deltah_h32_32x32x128x128x64x64x0x1x1x1x1x1x1_warps4xstages3();
}


CUresult kda_deltah_h32_default(CUstream stream, CUdeviceptr k, CUdeviceptr v, CUdeviceptr w, CUdeviceptr v_new, CUdeviceptr g, CUdeviceptr gk, CUdeviceptr h, CUdeviceptr h0, CUdeviceptr ht, CUdeviceptr cu_seqlens, CUdeviceptr chunk_offsets, int32_t T, int32_t NH){
  return kda_deltah_h32(stream, k, v, w, v_new, g, gk, h, h0, ht, cu_seqlens, chunk_offsets, T, NH, 0);
}
